### PR TITLE
fix: handle NONE and NOASSERTION as relationship targets

### LINKED ISSUE #552: Handle `NONE` and `NOASSERTION` relationships in SPDX
Haven't seen them so far. However, technically it is possible to have a relationship with the target `NONE` or `NOASSERTION`. `NONE` seems simple, the latter I have no idea what to do with.

https://spdx.github.io/spdx-spec/v2.3/relationships-between-SPDX-elements/#1111-description

> In cases where there are "known unknowns", the use of the keyword `NOASSERTION` can be used on the right hand side of a relationship to indicate that the author is not asserting whether there are other SPDX elements (package/file/snippet) that are connected by relationships or not. That is, there could be some, but the author is not asserting one way or another.
>
> Similarly, the use of the keyword `NONE` can be used to indicate that an SPDX element (package/file/snippet) has no other elements connected by some relationship to it.

### PR DESCRIPTION
**Pull request by ctron**
Closes #552

### CODE REVIEW

File: modules/ingestor/src/graph/sbom/common/relationship.rs [hunk 1]
```diff
@@ -30,7 +30,27 @@ impl RelationshipCreator {
...
+        // The idea of `NOASSERTION` is to state that there is a relationship, but the element it
+        // relates to is unknown.
+        //
+        // The idea of `NONE` is to state there it is known that there is no relationship to that
+        // element.
+        //
+        // At the moment, both those pieces of information don't add value to our system and
+        // only cause complexity when storing. So we simply drop it.
+
+        if let ("NONE" | "NOASSERTION", _) | (_, "NONE" | "NOASSERTION") = (&*left, &*right) {
```
Comment (JimFuller-RedHat) [inline modules/ingestor/src/graph/sbom/common/relationship.rs:49]: might be worth putting a TODO: here as a flag to some poor future programmer ;) otherwise this looks good.

Comment (ctron) [reply modules/ingestor/src/graph/sbom/common/relationship.rs:51]: Added a line.

**Review by JimFuller-RedHat — APPROVED** [review]
LGTM
